server:
  port: 5555

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include:
        - "routes"
        - "health"
zuul:
  sensitive-headers:
  - Cookie, Authorization
spring:
  boot:
    admin:
      client:
        url: http://localhost:9090
  application:
    name: zuul