eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://localhost:8761
  instance:
    prefer-ip-address: true
server:
  port: 8761

spring:
  application:
    name: eureka
  boot:
    admin:
      client:
        url: http://localhost:9090
